Added careplans, goals history and diagnoses history explores
AlayaCare/rosetta-config pull request #55
Opened 2023-03-29 14:33 UTC by jagrutz

https://alayacare.atlassian.net/browse/SPX-1834

2023-03-29 15:51 UTC, Mathieu-Gilli commented on looker_config.json
> +      "label": "Careplans",
Please change label

2023-03-29 15:51 UTC, Mathieu-Gilli requested changes
Please change label

2023-03-29 16:57 UTC, jagrutz commented on looker_config.json
> +      "label": "Careplans",
Labels updated

2023-04-05 21:05 UTC, estheban approved these changes
LGTM

2023-04-05 21:12 UTC, Mathieu-Gilli approved these changes

2023-04-05 21:28 UTC, merged